# Generated by Django 4.0.4 on 2022-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_donation_pick_up_comment_alter_donation_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'donation', 'verbose_name_plural': 'donations'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
