# Generated by Django 4.0.4 on 2022-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_category_options_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
