# Generated by Django 4.0.4 on 2022-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_donation_address_donation_categories_donation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=22),
        ),
    ]
