# Generated by Django 4.0.4 on 2022-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_donation_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation2',
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
